# Generated by Django 5.2.17 on 2026-09-05 12:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Адрес')),
                ('accent_color', models.CharField(default='#FF766E', max_length=7, verbose_name='Цвет')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('usage_notes', models.TextField(blank=True, verbose_name='Условия использования')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Адрес страницы')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='Район')),
                ('metro', models.CharField(blank=True, max_length=120, verbose_name='Метро')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Сохраняются собственные координаты или точка, выбранная редактором.', null=True, srid=4326, verbose_name='Координаты')),
                ('entrance_notes', models.CharField(blank=True, max_length=255, verbose_name='Как найти вход')),
                ('parking_notes', models.CharField(blank=True, max_length=255, verbose_name='Парковка')),
                ('stroller_access', models.BooleanField(default=False, verbose_name='Можно с коляской')),
                ('accessible', models.BooleanField(default=False, verbose_name='Безбарьерный доступ')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('slug', models.SlugField(max_length=240, unique=True, verbose_name='Адрес страницы')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('source_url', models.URLField(blank=True, verbose_name='Страница первоисточника')),
                ('cover_url', models.URLField(blank=True, verbose_name='Ссылка на обложку')),
                ('age_from', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст от')),
                ('age_to', models.PositiveSmallIntegerField(default=14, verbose_name='Возраст до')),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена от')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатно')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность, минут')),
                ('activity_format', models.CharField(choices=[('indoor', 'В помещении'), ('outdoor', 'На улице'), ('both', 'В помещении и на улице')], default='indoor', max_length=12, verbose_name='Формат')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На модерации'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=12, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Популярное')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуем')),
                ('published_until', models.DateField(blank=True, null=True, verbose_name='Показывать до')),
                ('last_verified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.category', verbose_name='Категория')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.organizer', verbose_name='Организатор')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.source', verbose_name='Источник')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.venue', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('availability', models.CharField(choices=[('available', 'Есть места'), ('few', 'Мало мест'), ('sold_out', 'Мест нет'), ('unknown', 'Нужно уточнить')], default='unknown', max_length=12, verbose_name='Доступность')),
                ('booking_url', models.URLField(blank=True, verbose_name='Ссылка на запись')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ('starts_at',),
                'indexes': [models.Index(fields=['starts_at', 'availability'], name='session_search_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'published_until'], name='event_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'activity_format'], name='event_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('age_to__gte', models.F('age_from'))), name='event_age_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('price_from__gte', 0)), name='event_price_from_nonnegative'),
        ),
    ]
