# Generated by Django 5.2.17 on 2026-09-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="automated_collection_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Включайте только после проверки правил сайта и получения необходимых разрешений.",
                verbose_name="Автоматический сбор разрешён",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="feed_url",
            field=models.URLField(blank=True, verbose_name="Адрес ленты или раздела"),
        ),
        migrations.AddField(
            model_name="source",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="source",
            name="last_import_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последний импорт"),
        ),
        migrations.AddField(
            model_name="source",
            name="parser_code",
            field=models.SlugField(
                blank=True,
                help_text="Технический идентификатор адаптера источника.",
                max_length=80,
                verbose_name="Код парсера",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parser_code", ""), _negated=True),
                fields=("parser_code",),
                name="unique_nonempty_parser_code",
            ),
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="events/%Y/%m/", verbose_name="Изображение")),
                ("alt_text", models.CharField(blank=True, max_length=255, verbose_name="Описание изображения")),
                ("source_url", models.URLField(blank=True, verbose_name="Источник изображения")),
                (
                    "rights_note",
                    models.CharField(
                        blank=True,
                        help_text="Например: предоставлено организатором или собственная фотография.",
                        max_length=255,
                        verbose_name="Права на использование",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_cover", models.BooleanField(default=False, verbose_name="Обложка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Загружено")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение мероприятия",
                "verbose_name_plural": "Изображения мероприятия",
                "ordering": ("-is_cover", "sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("completed", "Завершён"),
                            ("partial", "Завершён с ошибками"),
                            ("failed", "Ошибка"),
                        ],
                        default="running",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("dry_run", models.BooleanField(default=False, verbose_name="Проверочный запуск")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Начало")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Окончание")),
                ("found_count", models.PositiveIntegerField(default=0, verbose_name="Найдено")),
                ("staged_count", models.PositiveIntegerField(default=0, verbose_name="Добавлено в очередь")),
                ("updated_count", models.PositiveIntegerField(default=0, verbose_name="Обновлено")),
                ("failed_count", models.PositiveIntegerField(default=0, verbose_name="Ошибок")),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_runs",
                        to="catalog.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запуск импорта",
                "verbose_name_plural": "Запуски импорта",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ImportedEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255, verbose_name="ID в источнике")),
                ("title", models.CharField(blank=True, max_length=220, verbose_name="Название")),
                ("source_url", models.URLField(blank=True, verbose_name="Страница первоисточника")),
                ("fingerprint", models.CharField(blank=True, max_length=64, verbose_name="Отпечаток данных")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая запись"),
                            ("review", "На проверке"),
                            ("ready", "Готово к переносу"),
                            ("imported", "Перенесено"),
                            ("skipped", "Пропущено"),
                            ("error", "Ошибка"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict, verbose_name="Исходные данные")),
                ("normalized_payload", models.JSONField(default=dict, verbose_name="Нормализованные данные")),
                ("validation_errors", models.JSONField(blank=True, default=list, verbose_name="Ошибки проверки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Получено")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_records",
                        to="catalog.event",
                        verbose_name="Созданное мероприятие",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imported_events",
                        to="catalog.source",
                        verbose_name="Источник",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="catalog.importrun",
                        verbose_name="Запуск импорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Импортированное мероприятие",
                "verbose_name_plural": "Очередь импорта",
                "ordering": ("-updated_at",),
                "indexes": [models.Index(fields=["status", "updated_at"], name="import_review_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("source", "external_id"), name="unique_source_external_event")
                ],
            },
        ),
    ]
